colors:
  primary: '#800080'
  analogous--primary: '#400080'
  analogous--primary-50: '#40008080'
  analogous--secondary: '#800040'
  analogous--secondary-50: '#800040b0'
  monochromatic--dark-deep: '#4d004d'